### ISSUE TITLE
Example error?

### ISSUE THREAD

**Issue by Skyfire852** [raywenderlich/da-materials#20]
https://github.com/raywenderlich/da-materials/blob/361d87b1e433f63172174347d25a80434e4f9ddc/03-types-and-operations/projects/mini_exercise/bin/mini_exercise.dart#L52

I think the correct answer here is:

 const myDetails = 'Hello, my name is $fullName';

**Comment by suragch** [comment]
Good catch! Thank you! This is fixed in the `editions/1.1` branch now.
